font_family SFMono Nerd Font
font_size 9
background_opacity 0.95
blur true
window_padding_width 8

# Rounded Corners (Hanya berfungsi jika WM mendukung/Compositor aktif)
# Namun Kitty lebih fokus pada padding untuk estetika ini.
