font_family SFMono Nerd Font
background_opacity 0.95
blur true


# --- Material 3 Green (Deep Botanical) ---

# Background & Foreground
background            #171d17
foreground            #e1e3df
selection_background  #005231
selection_foreground  #d2e8d1

# Cursor colors
cursor                #d2e8d1
cursor_text_color     #171d17

# URL underline color when hovering with mouse
url_color             #b6ffad

# Window Borders
active_border_color   #005231
inactive_border_color #424940

# Tab Bar Colors
active_tab_background   #005231
active_tab_foreground   #d2e8d1
inactive_tab_background #222a22
inactive_tab_foreground #8c9388

# The 16 Terminal Colors (Material 3 Palette)

# Black (Surface/Outline)
color0 #171d17
color8 #424940

# Red (Error)
color1 #ffb4ab
color9 #ffdad6

# Green (Primary)
color2  #a3ee10
color10 #b6ffad

# Yellow (Tertiary/Caution)
color3  #dfc08d
color11 #fbe0b1

# Blue (Secondary Accents)
color4  #a3caff
color12 #d2e4ff

# Magenta (Decorative)
color5  #d6bae8
color13 #f3daff

# Cyan (Special Accents)
color6  #a3ee10
color14 #d2e8d1

# White (Text)
color7  #e1e3df
color15 #f9faf6

# --- UI Tweaks (Material 3 Style) ---

# Padding (Biar teks tidak nempel ke pinggir)
window_padding_width 12

# Rounded Corners (Hanya berfungsi jika WM mendukung/Compositor aktif)
# Namun Kitty lebih fokus pada padding untuk estetika ini.
